### ISSUE TITLE
Lateral shift between two channel.

### ISSUE THREAD

**Issue by Gaurav2Ant** [celldetective/celldetective#11]
**Is your feature request related to a problem? Please describe.**

There is a shift in fluo channel compare to RICM(adhesion) channel. 
We create the mask on adhesion channel first and than use the same mask for measurements in fluo channel but due to shift in 2 channel our measurement result in Fluo channel is biased.

**Describe the solution you'd like**

We would like to add an feature which could be part of Preprocessing panel of the software. Which could look like the following

**Default**
Channel                                        x Shift      y Shift

Adhesion channel                          0                0
Fluo channel                                  0               0 
Bright field                                     0               0
---------------------- ---------------------------------

**User modified** 
Channel                                        x Shift      y Shift

Adhesion channel                          0                0
Fluo channel                                  -2              3 
Bright field                                     0                0

This correction could be applied  together with background correction in the correction apply box
![github](https://github.com/user-attachments/assets/17f0644b-fd65-428e-9dc9-ec43a0b3200c)

**Comment by remyeltorro** [comment]
Dear @Gaurav2Ant, thank you for the feature request. I understand that you have rigid shifts (constant in -x and -y) between some of your channels that need to be corrected. I am concerned that the shifts may be more complex than a simple offset and hard to estimate visually. 

Before considering the development of this feature, could you try to perform the correction with Fiji/ImageJ, using [TransformJ](https://imagescience.org/meijering/software/transformj/affine/)? This Fiji plugin has both a translation and affine transform module which could be enough for your data. If so, I can help you write a [macro](https://celldetective.readthedocs.io/en/latest/align_macro.html) to apply it to your images in an experiment folder.
