### ISSUE TITLE
[BUG] Segmentation and Tracking Window not opening.

### ISSUE THREAD

**Issue by Gaurav2Ant** [celldetective/celldetective#12]
**Describe the bug**
I have recently updated the cell detective to new version.
While clicking on the eye near the segmentation I am unable to see the Napari window.(see the image attached)
I proceed and did the tracking and i found same issue with the tracking window its unable to open.
Although I could see Measure and Detect events window its working normal.

**To Reproduce**
1. Go to cell detective and upload the stack and after preprocessing (background correction).
2. Do the Segmentation
3. Click on Segmentation window to check the mask.
5. See error

**Expected behavior**
I would have expected to have a Napari window with segmentations.

**Screenshots**
![image](https://github.com/user-attachments/assets/5911b19f-2244-46ed-8def-1edf4604bf60)
![pastedImage (3)](https://github.com/user-attachments/assets/ebca6cde-f230-4f24-a7ff-3180201c7ae1)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Window

**Additional context**
After Clicking Okay its asking me Would you like to pass empty frames to fix the asymmetry? and i tried both yes and no but nothing worked, for yes i got following response on the terminal.
**_Automatically detected stack length: 56...
Automatically detected stack length: 56...
(56, 1002, 1004, 2)
Error cannot import name 'version_short' from 'pydantic.version' (C:\Users\laurent\anaconda3\Lib\site-packages\pydantic\version.cp311-win_amd64.pyd)_**

**Comment by remyeltorro** [comment]
Hello @Gaurav2Ant,
Thank you for reaching out. It seems that one of the process triggered when calling napari is trying to locate a version in the pydantic package that cannot be found with your current pydantic version. 

Could you show me the version returned by  `pip show pydantic` and `pip show napari`, if you type these commands in your terminal? This way I can pinpoint the pydantic version that is creating the issue.

As for a fix, you could try to update `napari` first since it has a requirement on the pydantic version: `pip install --upgrade napari`.

**Comment by Gaurav2Ant** [comment]
Hello @remyeltorro 

Thanks for your suggestion. _pip install --upgrade napari_ solved the issue.
I can see the Napari window back.

best,
Gaurav

**Comment by remyeltorro** [comment]
Very well, if you managed to get the `napari` / `pydantic` versions that were not working with the `pip show` command before the fix, please tell me, so that I can add this information to the requirements,
Best
Rémy

**Comment by Gaurav2Ant** [comment]
Sorry!
I don´t checked the version before. I tried to update Napari first and it worked. 
Currently the versions are
*Name: pydantic
Version: 1.10.12*

*Name: napari
Version: 0.5.4*

**Comment by remyeltorro** [comment]
Thank you, I will then close this discussion.
